# Generated by Django 2.2.16 on 2022-01-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["-id"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
    ]
