# Generated by Django 2.2.16 on 2022-01-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20220117_0106"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["-id"],
                "verbose_name": "Произведене",
                "verbose_name_plural": "Произведения",
            },
        ),
    ]
