# Generated by Django 2.2.16 on 2022-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_title_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
