# Generated by Django 2.2.16 on 2022-01-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_auto_20220118_1636"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["pub_date"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
